runtime: nodejs18
env: standard

env_variables:
  INSTANCE_CONNECTION_NAME: umkm-culinary-recommendation:us-central1:ucr-db
  INSTANCE_HOST: 34.172.130.194
  DB_USER: root
  DB_PASS: db123123
  DB_NAME: UCR
  DB_PORT: 3307
  PORT: 8080
  SECRET_KEY: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMTI1MDg2NCwiaWF0IjoxNzAxMjUwODY0fQ.B0AaPuy5RQIGkJn3IVYhE8LWWtbjqEbhZyWoFYsNTbI
